<a href="https://colab.research.google.com/github/iasmimsilveira/Estudos_dados/blob/main/Deputados.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Aula de Pandas

### Gasto dos Deputados Federais

In [36]:
import pandas as pd
from pandas.api.types import is_string_dtype
import numpy as np

In [35]:
df_2018 = pd.read_csv('Ano-2018.csv', sep=';', parse_dates=['datEmissao'])

In [32]:
df_2018.tail().T

                                       292400  ...                     292404
txNomeParlamentar                FELIPE SOUZA  ...               FELIPE SOUZA
ideCadastro                            205234  ...                     205234
nuCarteiraParlamentar                     620  ...                        620
nuLegislatura                            2015  ...                       2015
sgUF                                       AM  ...                         AM
sgPartido                                 PHS  ...                        PHS
codLegislatura                             55  ...                         55
numSubCota                                 10  ...                        999
txtDescricao                        TELEFONIA  ...      Emissão Bilhete Aéreo
numEspecificacaoSubCota                     0  ...                          0
txtDescricaoEspecificacao                 NaN  ...                        NaN
txtFornecedor                           RAMAL  ...            Cia Aérea - TAM
txtCNPJCPF                 000.000.000/0000-6  ...         020.128.620/0016-0
txtNumero                             6736164  ...   Bilhete: 957-2187.232544
indTipoDocumento                            0  ...                          0
datEmissao                                NaT  ...        2018-12-28 00:00:00
vlrDocumento                            29.91  ...                    1738.17
vlrGlosa                                    0  ...                          0
vlrLiquido                              29.91  ...                    1738.17
numMes                                     12  ...                         12
numAno                                   2018  ...                       2018
numParcela                                  0  ...                          0
txtPassageiro                             NaN  ...  RAIMUNDO N PINHEIRO SOUZA
txtTrecho                                 NaN  ...                    MAO/GRU
numLote                                     0  ...                          0
numRessarcimento                            0  ...                          0
vlrRestituicao                            NaN  ...                        NaN
nuDeputadoId                             3188  ...                       3188
ideDocumento                                0  ...                    1630187

[29 rows x 5 columns]

Filtro por deputados

In [33]:
df_2018 = df_2018[pd.isna(df_2018['sgPartido']) == False]
df_2018

       txNomeParlamentar  ideCadastro  ...  nuDeputadoId  ideDocumento
752         SILVIO COSTA       4930.0  ...          1973       6516403
753         SILVIO COSTA       4930.0  ...          1973       6529805
754         SILVIO COSTA       4930.0  ...          1973       6551866
755         SILVIO COSTA       4930.0  ...          1973       6610155
756         SILVIO COSTA       4930.0  ...          1973       6633681
...                  ...          ...  ...           ...           ...
292400      FELIPE SOUZA     205234.0  ...          3188             0
292401      FELIPE SOUZA     205234.0  ...          3188       6729488
292402      FELIPE SOUZA     205234.0  ...          3188       6729939
292403      FELIPE SOUZA     205234.0  ...          3188       6737772
292404      FELIPE SOUZA     205234.0  ...          3188       1630187

[291653 rows x 29 columns]

In [37]:
gasto = df_2018.groupby(['txNomeParlamentar', 'sgPartido'])['vlrDocumento'].sum().sorte_values(ascending=False)
gasto

AttributeError: ignored

#Gasto por Partido
###Quantos deputados tem em cada partido ?

In [12]:
df_2018['txNomeParlamentar'].value_counts()

DIEGO GARCIA           1931
JORGE TADEU MUDALEN    1753
CAPITÃO AUGUSTO        1666
HENRIQUE FONTANA       1483
DIMAS FABIANO          1409
                       ...
FELIPE SOUZA             14
AVANTE                    7
PSOL                      6
PSD                       6
PHS                       2
Name: txNomeParlamentar, Length: 568, dtype: int64

In [23]:
df_2018.groupby(['sgPartido'])['txNomeParlamentar'].nunique()

sgPartido
AVANTE            6
DEM              45
MDB              57
PATRI             5
PCdoB            13
PDT              24
PHS               5
PODE             20
PP               55
PPL               1
PPS              10
PR               41
PRB              23
PROS             11
PSB              28
PSC              10
PSD              39
PSDB             52
PSL               9
PSOL              6
PT               62
PTB              16
PV                4
REDE              2
SOLIDARIEDADE    11
Name: txNomeParlamentar, dtype: int64

In [28]:
partidos = df_2018.groupby(['sgPartido'])['txNomeParlamentar'].nunique()

In [24]:
gasto = df_2018.groupby(['sgPartido'])['vlrDocumento'].sum()

In [25]:
gasto = df_2018.groupby(['sgPartido'])['vlrDocumento'].sum()

In [29]:
df = pd.concat([gasto, partidos], axis=1)
df["gastosDeputados"] = df["vlrDocumento"] / df["txNomeParlamentar"]
df.sort_values(by=['gastosDeputados'], ascending=False)

               vlrDocumento  txNomeParlamentar  gastosDeputados
sgPartido
PPL            4.849136e+05                  1    484913.560000
PTB            7.412313e+06                 16    463269.580000
PROS           4.809456e+06                 11    437223.229091
PT             2.657885e+07                 62    428691.181613
AVANTE         2.541253e+06                  6    423542.103333
PSB            1.150624e+07                 28    410937.146429
PSD            1.576786e+07                 39    404304.022821
PATRI          2.014903e+06                  5    402980.550000
DEM            1.791585e+07                 45    398129.974444
PRB            9.046844e+06                 23    393341.028696
PR             1.602908e+07                 41    390953.070488
MDB            2.186256e+07                 57    383553.716842
PODE           7.653522e+06                 20    382676.100500
PP             2.101120e+07                 55    382021.786364
PCdoB          4.917707e+06                 13    378285.156923
PHS            1.882794e+06                  5    376558.706000
PDT            8.856811e+06                 24    369033.783750
PSDB           1.904700e+07                 52    366288.485577
SOLIDARIEDADE  3.855729e+06                 11    350520.801818
PPS            3.463451e+06                 10    346345.112000
PSC            3.398525e+06                 10    339852.457000
REDE           6.714933e+05                  2    335746.625000
PSOL           1.998710e+06                  6    333118.308333
PSL            2.793127e+06                  9    310347.418889
PV             1.100695e+06                  4    275173.662500

In [ ]:
### Quais meses os deputados gastam mais?